language: node_js

node_js:
- '0.11'
- '0.10'
- '0.8'

before_script:
- npm install -g grunt-cli

env:
  global:
  - secure: LYnal8p+3OLLxE7K23eITZVbnDSMtOlorsdalhHzo1dcFoqUBPOLjkSp73octhjpDZp6qunHcMih5625tpGtFsMlMNIyg5dAgCKG1jGTkPgiJHqhc8aY2LV+/Ca1l08jjFINWV6OH5Z6lARiOilQxQ3xtTq2cMryzjWHrPXJ4+E=
  - secure: hWngKcmfC3eiYu8FL/VYc8AuKTc9gXzrbwMqv+rAlq6woZUiQSgpITX7+zNdQPSH0OkLj9FvUDJx1ay5r5y7EqDfcokUFni+T1f23yqevo4hKX79Eg9CqOCXiYU2tBTpKeJuVCgagMie6F0wqp69PxSU+Q9vnbzhiYX5rUvNhO4=
